require: rubocop-rspec

Bundler/OrderedGems:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Metrics/LineLength:
  Max: 120
  Exclude:
    - 'Gemfile'
Rails/SkipsModelValidations:
  Exclude:
    - 'app/models/jira_issues_and_pushes.rb'
Rails/HttpPositionalArguments:
  Enabled: false
Rails/ApplicationRecord:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/WordArray:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 9
RSpec/BeforeAfterAll:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'app/models/concerns/errors_json.rb'
Style/VariableNumber:
  Exclude:
    - 'spec/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/FileName:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
Style/DoubleNegation:
  Enabled: false
AllCops:
  Include:
    - '**/*.rb'
  Exclude:
    - 'spec/fixtures/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
