---
apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/pre_deploy_checker: 'true'
  namespace: jenkins
  name: pre_deploy_checker
spec:
  tolerations:
  - key: dedicated
    operator: Equal
    value: jenkins
    effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kops.k8s.io/instancegroup
            operator: In
            values:
            - jenkins
  containers:
  - name: ruby
    image: ruby:2.6.5
    tty: true
    resources:
      requests:
        memory: "100Mi"
    command:
    - cat
  - name: docker
    image: docker:19.03.8
    tty: true
    resources:
      requests:
        memory: "512Mi"
    command:
    - cat
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
  - name: mysql
    image: mysql:5.7.26
    env:
     - name: MYSQL_DATABASE
       value: predeploychecker_test
     - name: MYSQL_USER
       value: dev
     - name: MYSQL_PASSWORD
       value: dev
     - name: MYSQL_RANDOM_ROOT_PASSWORD
       value: true
    resources:
      requests:
        memory: "256Mi"
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
      type: Socket
