default: &default
  adapter: mysql2
  pool: 5
  username: <%= ENV['DATABASE_USER'] || "rr_dev" %>
  password: <%= ENV['DATABASE_PASS'] || "dev" %>
  host: <%= File.exist?('/tmp/mysql.sock') ? 'localhost' : '127.0.0.1' %>

test:
  <<: *default
  database: predeploychecker_test

development:
  <<: *default
  database: predeploychecker_dev

staging:
  adapter: mysql2
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

production:
  adapter: mysql2
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
