# InvocaSecrets setup
# Used to access app secrets

email:
  send_grid:
    invoca_net:
      smtp:
        address: smtp.sendgrid.net
        authentication: login
        domain: www.invoca.net
        password: pwd1234
        port: 2525
        user_name: "hosting+invoca_staging@invoca.com"
pre_deploy_checker:
  api:
    auth_key: key1234
