# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 31c2079e9fb23c3d60c616084313eb95e688aed50d14cb19ea0995266c73c7862b8205049c5ea1cce5e20f3e5c14fe3ac2311763c1ddcdc3077db1c3237fa620
  github_user_name: <%= ENV["GITHUB_USER_NAME"] %>
  github_password: <%= ENV["GITHUB_PASSWORD"] %>
  jira:
    site: <%= ENV["JIRA_SITE"] %>
    consumer_key: <%= ENV["JIRA_CONSUMER_KEY"] %>
    access_token: <%= ENV["JIRA_ACCESS_TOKEN"] %>
    access_key: <%= ENV["JIRA_ACCESS_KEY"] %>
    private_key_file: <%= ENV["JIRA_PRIVATE_KEY_FILE"] %>
  mailer_smtp_settings: <%= ENV["MAILER_SMTP_SETTINGS"] || "{}" %>

test:
  secret_key_base: 4fb8f2d4bb5cdc812ffd6e3ba4e0e364dd529ec0f6eb6204a4dbbfff7350a5b05f91df5720eb09717a16a4a37e2bd8aa58b2d3c552c5998b17b9907eead45328
  github_user_name: 'fake_github_user_name'
  github_password: 'fake_githib_password'
  jira:
    site: 'https://test.atlassian.net'
    consumer_key: 'test_consumer_key'
    access_token: 'test_access_token'
    access_key: 'test_access_key'
    private_key_file: './spec/fixtures/rsakey.pem'
  mailer_smtp_settings: <%= ENV["MAILER_SMTP_SETTINGS"] || {}%>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_user_name: <%= ENV["GITHUB_USER_NAME"] %>
  github_password: <%= ENV["GITHUB_PASSWORD"] %>
  jira:
    site: <%= ENV["JIRA_SITE"] %>
    consumer_key: <%= ENV["JIRA_CONSUMER_KEY"] %>
    access_token: <%= ENV["JIRA_ACCESS_TOKEN"] %>
    access_key: <%= ENV["JIRA_ACCESS_KEY"] %>
    private_key_file: <%= ENV["JIRA_PRIVATE_KEY_FILE"] %>
  mailer_smtp_settings: <%= ENV["MAILER_SMTP_SETTINGS"] || "{}" %>
